name: template_env
### Note that you could remove all the version tags in this document
### to get conda/mamba to install the (inter-compatible) latest version 
### of all dependencies;
### When you finish the project, you can copy the version numbers from 
### `conda list -n env_name` to this document, so you freeze them for the next user.

channels:
- defaults
- nvidia
dependencies:
- python>=3.10, <3.11 # Needed to run python
- pip # Needed to enable pip install inside conda envs,
- ipykernel # for notebook

# Below are examples of project-specific python and R packages (including versions)

# python packages
- numpy
- pandas
- seaborn
- matplotlib
- scikit-learn
- tqdm 
- IProgress 
# pytorch
- pytorch=*=*cuda*
- pytorch::torchvision=0.16.0 
#need to fixate this version, else could result in earlier version of torchvision and pytorch being installed
# the earlier version resulted in extremely high cpu usage and slow run even after controlling
# for number of threads and number of workers.

# for general DNN training
- conda-forge::lightning
- conda-forge::ipywidgets
- conda-forge::optuna

- sebp::scikit-survival